swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /filtroContrato/:
    get:
      tags:
      - filtroContrato
      description: get Contatoscontrato
      operationId: ContatoscontratoController.GetAll
      parameters:
      - in: query
        name: NumContrato
        description: Numero del contrato
        required: true
        type: string
      - in: query
        name: Vigencia
        description: Vigencia del contrato,, para evitar el filtro se debe de mandar
          un 0 (cero)
        required: true
        type: string
      - in: query
        name: SupID
        description: Identificacion del supervisor
        required: true
        type: string
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /filtroProveedor/:
    get:
      tags:
      - filtroProveedor
      description: get ContratosProveedor
      operationId: ContratosProveedorController.GetAll
      parameters:
      - in: query
        name: ProvID
        description: ID del Proveedor
        required: true
        type: string
      - in: query
        name: SupID
        description: Identificacion del supervisor, para evitar el filtro se debe
          de mandar un 0 (cero)
        required: true
        type: string
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
tags:
- name: filtroContrato
  description: |
    ContatoscontratoController ... Filtro para tener lista de contratos segun su vigencia y los proveedores de estos
- name: filtroProveedor
  description: |
    ContratosProveedorController ... Filtro para tener lista de contratos de un proveedor
