swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /filtroContrato/:
    get:
      tags:
      - filtroContrato
      description: get Contatoscontrato
      operationId: ContatoscontratoController.GetAll
      parameters:
      - in: query
        name: NumContrato
        description: Numero del contrato
        required: true
        type: string
      - in: query
        name: Vigencia
        description: Vigencia del contrato,, para evitar el filtro se debe de mandar
          un 0 (cero)
        required: true
        type: string
      - in: query
        name: SupID
        description: Identificacion del supervisor
        required: true
        type: string
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /filtroMixto/:
    get:
      tags:
      - filtroMixto
      description: get Filtromixto
      operationId: FiltromixtoController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Filtromixto'
        "403":
          description: ""
  /filtroProveedor/:
    get:
      tags:
      - filtroProveedor
      description: get ContratosProveedor
      operationId: ContratosProveedorController.GetAll
      parameters:
      - in: query
        name: ProvID
        description: ID del Proveedor
        required: true
        type: string
      - in: query
        name: SupID
        description: Identificacion del supervisor, para evitar el filtro se debe
          de mandar un 0 (cero)
        required: true
        type: string
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
definitions:
  models.Filtromixto:
    title: Filtromixto
    type: object
tags:
- name: filtroContrato
  description: |
    ContatoscontratoController ... Filtro para tener lista de contratos segun su vigencia y los proveedores de estos
- name: filtroProveedor
  description: |
    ContratosProveedorController ... Filtro para tener lista de contratos de un proveedor
- name: filtroMixto
  description: |
    FiltromixtoController operations for Filtromixto
